#!/usr/bin/env bash
if [[  ! -v DRESTICRC ]]
then
	DRESTICRC="${HOME}/.config/restic.conf"
fi

printf "+++ %s: drestic is restic with defaults - \$DRESTICRC=%s\n" "$(readlink -f "${0}")" "${DRESTICRC}"

if [[ -e "${DRESTICRC}" ]]
then
	set -o allexport
	cat "${DRESTICRC}"
	source "${DRESTICRC}"
	set +o allexport
else
	printf "\n%s not found.\n" "${DRESTICRC}"
	exit 255
fi

if [[ "${1}" == 'backup' ]]
then
	exec restic "$@" ${RESTIC__BACKUP_OPTS} ${RESTIC_EXCLUDES} ${RESTIC_INCLUDES}
elif [[ "${1}" == 'forget' ]]
then
	exec restic "$@" ${RESTIC_RETENTION}
else
	exec restic "$@"
fi
